"""initial_schema

Revision ID: 88865c985b72
Revises: 
Create Date: 2026-06-14 14:17:05.563787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88865c985b72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='suitestatus'), nullable=False),
    sa.Column('yaml_input_hash', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_url', sa.String(length=2048), nullable=False),
    sa.Column('protocol', sa.Enum('HTTP', 'WEBSOCKET', name='protocoldb'), nullable=False),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('total_scenarios', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_report_blob_key', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_id')
    )
    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suite_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('POSITIVE', 'NEGATIVE', name='scenariotypedb'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('persona_entity_id', sa.String(length=255), nullable=True),
    sa.Column('turns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assertions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depends_on', sa.UUID(), nullable=True),
    sa.Column('depends_on_type', sa.Enum('PROBE', 'DEFENSIVE_PROBE', name='dependsontypedb'), nullable=True),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'SKIPPED', name='scenariostatus'), nullable=False),
    sa.Column('verdict', sa.Enum('SUCCESS', 'SUCCESS_UNVERIFIED', 'FAILURE', 'FAILURE_CORRUPT', 'SUSPECT', 'ERROR', name='verdictdb'), nullable=True),
    sa.Column('verdict_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_blob_key', sa.String(length=512), nullable=True),
    sa.Column('world_state_before_key', sa.String(length=512), nullable=True),
    sa.Column('world_state_after_key', sa.String(length=512), nullable=True),
    sa.Column('patch_ops_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['depends_on'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenarios')
    op.drop_table('reports')
    op.drop_table('suites')
    # ### end Alembic commands ###
